In [182]:
from pathlib import Path, PurePath
import numpy as np
import pandas as pd
import os
from analysis import read_behaviors, return_genome
from utility.util_functions import euclidean_distance
from deap import creator, base, tools
import pickle

In [35]:
behaviors_file = sorted(Path('data/results/')
                        .glob('transferability_simulation_*/behavioral_features.dat'))
sim_file = 'data/results/transferability_simulation_5/deap_inds/1_genome_.pkl'
thymio_file = 'data/results/transferability_simulation_5/deap_inds/1_transformed_genome_.pkl'

behaviors = read_behaviors(behaviors_file)

In [36]:
behavior = behaviors[4]

columns = [
        'avg_left', 'avg_right',
        's1', 's2', 's3', 's4', 's5', 's6', 's7',
        'area0_percentage',
        'area1_percentage',
        'area2_percentage',
    ]

In [37]:
b = behavior.loc[:1, columns]

In [38]:
euclidean_distance(b.iloc[0], b.iloc[1])

0.022050881668069677

In [39]:
creator.create("FitnessMax", base.Fitness, weights=(1.0, -1.0, 1.0))
creator.create("Individual", list,
               fitness=creator.FitnessMax, model=None)
Individual = creator.Individual

In [40]:
with open(sim_file, 'rb') as f:
    sim = pickle.load(f)

In [41]:
sim.position

array([[0.15927598, 0.22249341],
       [0.13696139, 0.22522895],
       [0.11506245, 0.22693148]])

In [42]:
with open(thymio_file, 'rb') as f:
    thymio = pickle.load(f)

In [44]:
euclidean_distance(sim.position, thymio.position)

0.05196160720926865

In [45]:
euclidean_distance(sim.features, thymio.features)

0.022050887733992806

In [175]:
import random
[random.uniform(-1.0, 1.0) for _ in range(2)]

[-0.24978936549763286, 0.047915910077206414]

In [177]:
sim.weights

[array([[-0.307995  ,  0.6681611 , -0.7416936 , -0.5644486 ,  0.9610636 ],
        [ 0.74798936, -0.7110613 , -0.62795943, -0.6547123 ,  0.9362017 ],
        [-0.5420197 ,  0.65897745,  0.3151876 ,  0.02636799, -0.95336163],
        [ 0.94587624,  0.01883841, -0.25195858, -0.03406605, -0.36826244],
        [-0.5187096 ,  0.32831642, -0.80290216,  0.1882105 ,  0.6742661 ],
        [-0.92964226,  0.49430266, -0.03373729,  0.17966901, -0.05190301],
        [-0.59988534,  0.06831679, -0.33073416,  0.13584384, -0.58154   ]],
       dtype=float32),
 array([ 0.13479938, -0.3661307 ,  0.06657075,  0.34242183, -0.08932994],
       dtype=float32),
 array([[-0.41458705, -0.3175319 ],
        [ 0.40408075, -0.84704614],
        [ 0.24251512,  0.41672325],
        [-0.07850963,  0.18476094],
        [-0.13206886, -0.13514468]], dtype=float32),
 array([-0.9353474, -0.8505964], dtype=float32)]

In [181]:
sim.fitness.values

(0.2926078065907653, 0.05196160720926865, 0.022050887733992806)

In [183]:
sim[:10]

[-0.3079949964941153,
 0.6681610721738844,
 -0.741693598644515,
 -0.5644486002400868,
 0.9610636182081738,
 0.7479893859986246,
 -0.7110613094205827,
 -0.6279594303678795,
 -0.6547122988609337,
 0.9362016832146036]

In [505]:
tools.mutGaussian(sim[:10], 0.0, .2, 0.7)

([-0.3079949964941153,
  0.6681610721738844,
  -0.741693598644515,
  -0.5644486002400868,
  0.6053906931950257,
  0.7479893859986246,
  -0.7722418566066982,
  -0.6279594303678795,
  -0.6547122988609337,
  0.9362016832146036],)