In [1]:
from pathlib import Path, PurePath
import numpy as np
import pandas as pd
import os
from analysis import read_behaviors, return_genome
from utility.util_functions import euclidean_distance
from deap import creator, base, tools
import pickle

In [2]:
behaviors_file = sorted(Path('data/results/')
                        .glob('transferability_simulation_*/behavioral_features.dat'))
sim_file = 'data/results/transferability_simulation_5/deap_inds/1_genome_.pkl'
thymio_file = 'data/results/transferability_simulation_5/deap_inds/1_transformed_genome_.pkl'

behaviors = read_behaviors(behaviors_file)

In [3]:
behavior = behaviors[4]

columns = [
        'avg_left', 'avg_right',
        's1', 's2', 's3', 's4', 's5', 's6', 's7',
        'area0_percentage',
        'area1_percentage',
        'area2_percentage',
    ]

In [4]:
b = behavior.loc[:1, columns]

In [5]:
euclidean_distance(b.iloc[0], b.iloc[1])

0.022050881668069677

In [6]:
creator.create("FitnessMax", base.Fitness, weights=(1.0, -1.0, 1.0))
creator.create("Individual", list,
               fitness=creator.FitnessMax, model=None)
Individual = creator.Individual

In [7]:
with open(sim_file, 'rb') as f:
    sim = pickle.load(f)

In [8]:
sim.position

array([[0.15927598, 0.22249341],
       [0.13696139, 0.22522895],
       [0.11506245, 0.22693148]])

In [9]:
with open(thymio_file, 'rb') as f:
    thymio = pickle.load(f)

In [10]:
euclidean_distance(sim.position, thymio.position)

0.05196160720926865

In [11]:
euclidean_distance(sim.features, thymio.features)

0.022050887733992806

In [13]:
thymio.position[:len(sim.position)]

[array([0.1498599 , 0.19914965]),
 array([0.1101361 , 0.20065616]),
 array([0.10492994, 0.20162676])]

In [52]:
def calc_str_disparity(transfered, simulation):
    
    if len(transfered) >  len(simulation):
        t = np.array(transfered[:len(simulation)])
        s = np.array(simulation)
    elif len(simulation) > len(transfered):
        t = np.array(transfered)
        s = np.array(simulation[:len(transfered)])
    else:
        t = np.array(transfered)
        s = np.array(simulation)
        
    t_mean = np.mean(t, axis=0)
    s_mean = np.mean(s, axis=0)
    
    
    x = np.sum((np.power(s.T[0]-t.T[0], 2) / (s_mean[0]*t_mean[0])))
    y = np.sum((np.power(s.T[1]-t.T[1], 2) / (s_mean[1]*t_mean[1])))
    
    return x + y

In [37]:
sim.position

array([[0.15927598, 0.22249341],
       [0.13696139, 0.22522895],
       [0.11506245, 0.22693148]])

In [36]:
np.reshape(sim.position, (2, len(sim.position)))

array([[0.15927598, 0.22249341, 0.13696139],
       [0.22522895, 0.11506245, 0.22693148]])

In [38]:
np.array(sim.position).T

array([[0.15927598, 0.13696139, 0.11506245],
       [0.22249341, 0.22522895, 0.22693148]])

In [44]:
np.array(sim.position).T[0]

array([0.15927598, 0.13696139, 0.11506245])

In [43]:
np.array(thymio.position).T

array([[0.1498599 , 0.1101361 , 0.10492994, 0.10492994, 0.10492994,
        0.10492994, 0.10492994, 0.10492994, 0.10492994, 0.10492994,
        0.10528109, 0.10586636, 0.10586636, 0.10586636, 0.10586636,
        0.10586636, 0.10586636, 0.10586636, 0.10584222, 0.10586636,
        0.10586636, 0.10586636, 0.10586636, 0.10586636, 0.10584429,
        0.10586636, 0.10582774, 0.10586636, 0.10586636],
       [0.19914965, 0.20065616, 0.20162676, 0.20162676, 0.20162676,
        0.20162676, 0.20162676, 0.20162676, 0.20162676, 0.20162676,
        0.20162132, 0.20161227, 0.20161227, 0.20161227, 0.20161227,
        0.20161227, 0.20161227, 0.20161227, 0.20105642, 0.20161227,
        0.20161227, 0.20161227, 0.20161227, 0.20161227, 0.20110407,
        0.20161227, 0.2007229 , 0.20161227, 0.20161227]])

In [49]:
str_disparity(sim.position, thymio.position)

0.09430439663010301